export default [
    {
        id: 1,
        title: "Munich",
        location: "Germany",
        googleMapsUrl: "https://goo.gl/maps/DHcjemf9GsczpvTK8",
        visitDate: "June 2010",
        description: "A city with a big heart, as suave as it is easygoing, buzzing and yet tranquil. Munich is Germany's lifestyle capital. And on top of all this, it boasts one of the country's most beautiful squares: Marienplatz, at the heart of the city and home to the Old and New Town Halls.", 
        coverImg: "munich.jpg",
        altText: "Beers, Brezn, Sausages",
        link: "https://en.wikipedia.org/wiki/Munich",
    },
    {
        id: 2,
        title: "San Juan",
        location: "Puerto Rico",
        googleMapsUrl: "https://goo.gl/maps/AP2PVGQd7HVfEErC9",
        visitDate: "February 2012",
        description: "Cobblestoned Old San Juan features colorful Spanish colonial buildings and 16th-century landmarks including El Morro and La Fortaleza, massive fortresses with sweeping ocean views, as well as the Paseo de la Princesa bayside promenade.", 
        coverImg: "sanJuan.jpg",
        altText: "pina colada, el morro, salsa",
        link: "https://en.wikipedia.org/wiki/San_Juan,_Puerto_Rico",
    },    
    {
        id: 3,
        title: "Prague",
        location: "Czech Republic",
        googleMapsUrl: "https://goo.gl/maps/vFtRRLQ1VkarAMmH9",
        visitDate: "December 2010",
        description: "The bohemian allure and fairytale features of Prague make it a perfect destination for culture vultures who want to immerse themselves in history, art, music, and architecture. You could devote an entire day to exploring Prazsky hrad (Prague Castle), then refuel over a hearty dinner at a classic Czech tavern.", 
        coverImg: "prague.jpg",
        altText: "towers, oblatzki, Pilsener",
        link: "https://en.wikipedia.org/wiki/Prague",
    },  
    {
        id: 4,
        title: "Montreal",
        location: "Canada",
        googleMapsUrl: "https://goo.gl/maps/cUfTwupq9ubwu8x49",
        visitDate: "August 2015",
        description: "Montreal, c’est si bon! This French-speaking city is considered the cultural capital of Canada, and is a cosmopolitan celebration of Québécois style. A stroll around the cobblestone streets and grand buildings of Vieux-Montréal will give you a taste of European flavor.", 
        coverImg: "montreal.jpg",
        altText: "poutine, tart beers, eclairs",
        link: "https://en.wikipedia.org/wiki/Montreal",
    },
    {
        id: 5,
        title: "Garmisch-Partenkirchen",
        location: "Germany",
        googleMapsUrl: "https://goo.gl/maps/ZnvVVSyzYiTGjADt6",
        visitDate: "May 2016",
        description: "Garmisch-Partenkirchen is a great place from which to explore southern Germany.  It is located in the German Alps, just a few miles from the border with Austria, which we visited quite a bit.  With these mountains comes rain, particularly in the summer.", 
        coverImg: "garmisch.jpg",
        altText: "zugspitze, edelweiss, renzos",
        link: "https://en.wikipedia.org/wiki/Garmisch-Partenkirchen",
    },
    {
        id: 6,
        title: "Berchtesgaden",
        location: "Germany",
        googleMapsUrl: "https://goo.gl/maps/PHQHqegwtjoYPUKY6",
        visitDate: "May 2016",
        description: "Explore this charming little mountain town and sail on the Königssee, hike the alpine meadows, tour the salt mine and visit the local hofbräuhaus.", 
        coverImg: "berchtes.jpg",
        altText: "alps, koenigsee, spaetzle",
        link: "https://en.wikipedia.org/wiki/Berchtesgaden",
    },
    {
        id: 7,
        title: "Zaanse Schans",
        location: "Netherlands",
        googleMapsUrl: "https://goo.gl/maps/H7BmSTv3Ji4nzUJu6",
        visitDate: "May 2016",
        description: "The Zaanse Schans is a unique part of the Netherlands, with wooden houses, mills, barns and workshops. Browse the shops or treat yourself at the pancake restaurant.",        
        coverImg: "zaanSe.jpg",
        altText: "Kaas, Kibbeling, Sativas",
        link: "https://en.wikipedia.org/wiki/Zaanse_Schans",
    },
    {
        id: 8,
        title: "Sirmione",
        location: "Italy",
        googleMapsUrl: "https://goo.gl/maps/yBuFHsiim9SDRreP9",
        visitDate: "June 2017",
        description: "Perched on the tip of a long, narrow peninsula, Sirmione is a medieval town surrounded by gardens, thermal spas, beaches, and the aquamarine water of Lake Garda.",
        coverImg: "sirmiOne.jpg",
        altText: "Lemons, Pasta, Dolce Vita",
        link: "https://en.wikipedia.org/wiki/Sirmione",
    },
    {
        id: 9,
        title: "Amsterdam",
        location: "Netherlands",
        googleMapsUrl: "https://goo.gl/maps/pP1KFLYy9VeyUW7Z8",
        visitDate: "May 2018",
        description: "Picturesque canals and bridges. Historic homes with brightly-colored bicycles and tulip stands around town. Amsterdam is a full-blown fairytale.", 
        coverImg: "amsterDam.jpg",
        altText: "Bikes, Pannekoeken, Sativas",
        link: "https://en.wikipedia.org/wiki/Amsterdam",
    },     
    {
        id: 10,
        title: "Verona",
        location: "Italy",
        googleMapsUrl: "https://goo.gl/maps/4NWUSCcg43p4vjsT8",
        visitDate: "May 2018",
        description: "Verona is a city in northern Italy’s Veneto region, with a medieval old town built between the meandering Adige River. It’s famous for being the setting of Shakespeare’s Romeo and Juliet. A 14th-century residence with a tiny balcony overlooking a courtyard is said be Juliet’s House.", 
        coverImg: "verona.jpg",
        altText: "Romeo, Juliet, Risotto",
        link: "https://en.wikipedia.org/wiki/Verona",
    },
    {
        id: 11,
        title: "Denver",
        location: "Colorado, USA",
        googleMapsUrl: "https://goo.gl/maps/uJNhb4NwtLKw31kP6",
        visitDate: "June 2016",
        description: "The capital of Colorado, nicknamed the “Mile High City” because its official elevation is exactly one mile above sea level, began as a settlement of gold seekers, many of them unsuccessful. ", 
        coverImg: "denver.jpg",
        altText: "hatch chile, mile high, OGs",
        link: "https://en.wikipedia.org/wiki/Denver",
    },
    {
        id: 12,
        title: "Vail",
        location: "Colorado, USA",
        googleMapsUrl: "https://goo.gl/maps/3mreJNMzfwNFbiub8",
        visitDate: "August 2018",
        description: "Nestled in the Colorado Rockies, Vail is a serene European-style village village where pedestrian-friendly streets wind between old-world Bavarian architecture and open to views of unencumbered wilderness. Stroll and explore shops and restaurants along Gore Creek and discover a special place where the fresh air makes life feel a bit lighter.", 
        coverImg: "vail'.jpg",
        altText: "mountains, ski paradise, craft beers",
        link: "https://en.wikipedia.org/wiki/Vail,_Colorado",
    }
    
]