export default [
    {
        id: 1,
        title: "Schloss Neuschwanstein",
        location: "Bavaria,Germany",
        googleMapsUrl: "https://goo.gl/maps/8XF8PFkfC5gW8k9f8",
        visitDate: "May 2015",
        description: "The fairytale castle Neuschwanstein is a popular sight in Germany. The castle in Bavaria was built by order of King Ludwig II and the inspiration for the Disney Cinderella castle.",
        coverImg: "castleNeu.jpg",
        altText: "iconic picture of Neuschwansein castle",
        link: "https://en.wikipedia.org/wiki/Neuschwanstein_Castle",
    },
    {
        id: 2,
        title: "Zaanse Schans",
        location: "Netherlands",
        googleMapsUrl: "https://goo.gl/maps/H7BmSTv3Ji4nzUJu6",
        visitDate: "May 2016",
        description: "The Zaanse Schans is a unique part of the Netherlands, with wooden houses, mills, barns and workshops. Browse the shops or treat yourself at the pancake restaurant.",        
        coverImg: "zaanSe.jpg",
        altText: "Kaas, Kibbeling, Sativas",
        link: "https://en.wikipedia.org/wiki/Zaanse_Schans",
    },
    {
        id: 3,
        title: "Sirmione",
        location: "Italy",
        googleMapsUrl: "https://goo.gl/maps/yBuFHsiim9SDRreP9",
        visitDate: "June 2017",
        description: "Perched on the tip of a long, narrow peninsula, Sirmione is a medieval town surrounded by gardens, thermal spas, beaches, and the aquamarine water of Lake Garda.",
        coverImg: "sirmiOne.jpg",
        altText: "Lemons, Pasta, Dolce Vita",
        link: "https://en.wikipedia.org/wiki/Sirmione",
    },
    {
        id: 4,
        title: "Amsterdam",
        location: "Netherlands",
        googleMapsUrl: "https://goo.gl/maps/pP1KFLYy9VeyUW7Z8",
        visitDate: "May 2018",
        description: "Picturesque canals and bridges. Historic homes with brightly-colored bicycles and tulip stands around town. Amsterdam is a full-blown fairytale.", 
        coverImg: "amsterDam.jpg",
        altText: "Bikes, Pannekoeken, Sativas",
        link: "https://en.wikipedia.org/wiki/Amsterdam",
    }
]